[micronaut.server]
host = "0.0.0.0"

[micronaut.application]
name = "bounce-world"

[jackson]
serializationInclusion = "ALWAYS"

[world]
width = 160
height = 88
scalingFactor = 4
updatesPerSecond = 10
shouldAutoStart = true
initialSpeed = 22
heartbeatTimeoutMillis = 40000
# one of "grid", or "right". 'grid' creates NxN locations for clients, 'right' just keeps adding them in a line to the right of previous, e.g. for a desk of computers at a festival.
locationPattern = "right"
enableWrapping = false
