
[versions]
kotlin-version = "2.1.0"
ktor-version = "3.0.3"
logback-version = "1.5.14"
joml-version = "1.10.8"
assertj-version = "3.27.0"
mockk-version = "1.13.14"
kotest-ktor-version = "2.0.0"

[libraries]
ktor-server-core = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor-version" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty-jvm", version.ref = "ktor-version" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback-version" }
ktor-server-config-yaml = { module = "io.ktor:ktor-server-config-yaml-jvm", version.ref = "ktor-version" }
joml-core = { module = "org.joml:joml", version.ref = "joml-version" }

ktor-server-test-host = { module = "io.ktor:ktor-server-test-host-jvm", version.ref = "ktor-version" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin-version" }
kotest-ktor-core = { module = "io.kotest.extensions:kotest-assertions-ktor", version.ref = "kotest-ktor-version" }
mockk-core = { module = "io.mockk:mockk", version.ref = "mockk-version" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj-version" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-version" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor-version" }
